---
schema-version: '1.1'
build:
  name: OpenSearch
  version: 3.0.0
  qualifier: beta1
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-al2-opensearch-build-v1
    args: -e JAVA_HOME=/opt/java/openjdk-21
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: tags/3.0.0-beta1
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: tags/3.0.0.0-beta1
    platforms:
      - linux
      - windows
  - name: opensearch-remote-metadata-sdk
    repository: https://github.com/opensearch-project/opensearch-remote-metadata-sdk.git
    ref: tags/3.0.0.0-beta1
    platforms:
      - linux
      - windows
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: tags/3.0.0.0-beta1
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: tags/3.0.0.0-beta1
    platforms:
      - linux
      - windows
  - name: ml-commons
    repository: https://github.com/bzhangam/ml-commons.git
    ref: 3.0.0-beta1
    platforms:
      - linux
      - windows
    depends_on:
      - common-utils
      - job-scheduler
      - opensearch-remote-metadata-sdk
  - name: neural-search
    repository: https://github.com/bzhangam/neural-search.git
    ref: 3.0.0-beta1
    platforms:
      - linux
      - windows
    depends_on:
      - ml-commons
      - k-NN
